---
- hosts: "BO-{{ store }}"
  gather_facts: no

  vars:
    # 114 
#    cheque_date: '06.02.2020'
#    cheque_no: 1272

    # 111
#    cheque_date: '03.03.2020'
#    cheque_no: 1948

#    loyalty_card: '777'


  tasks:

    - debug:
        var: cheque_date

    - set_fact:
        log_date: "{{ cheque_date|regex_replace('.*?(\\d+)\\.(\\d+)\\.(\\d+).*', '\\3\\2\\1') }}"

    - debug:
        var: log_date

    - name: Get loyalty operation
      set_fact:
        pos_name: "{{ 'POS-'+store+'-'+hostvars['localhost'].pos_override[ awx_workflow_job_id|string ]|default(pos) }}"

    - debug:
        var: pos_name

    - shell: zgrep -a 'Списано баллов' /usr/local/gkretail/pos/log/std_pos.log-{{ log_date }}*.gz |wc -l
      register: write_off_info
      ignore_errors: yes
      delegate_to: "{{ pos_name }}"

    - debug: 
        var: write_off_info.stdout

    - fail:
        msg: "<do_task> { template: 1000009, comment: {{ pos_name }} На кассе отсутствуют списания по картам лояльности за {{ cheque_date }} - требуется замена или чистка картридера }"
#        msg: "{{ pos_name }} На кассе отсутствуют списания по картам лояльности за {{ cheque_date }} - требуется замена или чистка картридера"
      when: write_off_info.stdout|int == 0

    - debug:
        msg: "{{ pos_name }} Найдены списания баллов по кассе за {{ cheque_date }}"

